### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by Ischdochegal** [sylwekb/face_swap#2]
Good day Sylwek Brzęczkowski 

First, I want to thank you for sharing this project, it's done great! Thank you very much.
I'm using your code (6_optical_flow_and_seamless_cloning.py) as part of a university project and had no problems setting it up. Thanks for the pipelock file. 
Although it works, I've noticeable lower fps and more lagging, than in your presentation. What could that be?
Also, when I'm close to the camera and I'm moving too fast, the code crashes and gives me to following error:

```
% python3 6_optical_flow_and_seamless_cloning.py pamela.jpg
Traceback (most recent call last):
  File "6_optical_flow_and_seamless_cloning.py", line 245, in <module>
    warp_triangle(img1, img1_warped, t1, t2)
  File "6_optical_flow_and_seamless_cloning.py", line 125, in warp_triangle
    img2[img2_cropped_slice] = img2[img2_cropped_slice] * ((1.0, 1.0, 1.0) - mask)
ValueError: operands could not be broadcast together with shapes (128,68,3) (153,68,3) 
```

About my setup, I'm running it on a Mac Pro with high specs (so the pc shouldn't be the problem) and with a 4K Webcam (Logitech BRIO).

I would be really glad for any help

Sincerely  
Kevin

**Comment by sylwekb** [comment]
hi @Ischdochegal 
1. there is no limiter for the fps that the program receives from the camera, so I assume yours is much higher than the built-in mac camera, please check that
2. Hard to tell, but it looks like the face in either the mask or the frame was too close to the edge of the camera field of view. 

btw kudos for pipfile go to @hwmrocker
